name: makanaki
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  provider: ^5.0.0
  shared_preferences: 2.0.6
  intl:
  google_fonts:
  animate_do:
  hexcolor: ^2.0.5
  hexagon: ^0.2.0-nullsafety.1
  dotted_border: ^2.0.0+3
  avatar_glow:
  fluttertoast: ^8.1.2
  swipe_cards: ^2.0.0+1
  pin_code_fields: ^7.4.0
  image_picker: ^0.8.6+3
  path: ^1.8.0
  permission_handler: ^8.1.4+2
  http:
  email_validator: ^2.1.17
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.0
  shimmer: ^2.0.0
  file_picker: ^5.2.5
  video_player: ^2.5.3
  cached_network_image:
  video_thumbnail: ^0.5.3
  numeral: ^2.0.1
  # preload_page_view: ^0.1.6
  # should_rebuild: ^1.0.1
  like_button: ^2.0.5
  animated_icon_button: ^1.0.2
  flutter_styled_toast: ^2.1.3
  gallery_saver: ^2.3.2
  timeago:
  async:
  firebase_messaging:
  firebase_core:
  cloud_firestore:
  flutter_paystack: ^1.0.7
  geolocator: ^9.0.2
  overlay_support: ^1.2.1
  restart_app:
  firebase_analytics:
  connectivity_plus: ^3.0.3
  location: ^4.3.0
  app_settings: ^4.2.0
  country_code_picker: ^3.0.0
  expansion_tile_card: ^2.0.0
  url_launcher: ^6.1.10
  flutter_dotenv: ^5.0.2
 



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

  flutter_lints: ^2.0.0
  build_runner:
  freezed: 0.14.0+1
  json_serializable: ^4.0.2


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/pic/MacaNacki.png"




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pic/
    - assets/icon/
    - secret.env


