name: macanacki
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+11

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  provider: ^6.0.1
  shared_preferences:

  google_fonts: ^4.0.1
  animate_do:
  hexcolor: ^2.0.5
  hexagon: ^0.2.0-nullsafety.1
  dotted_border: ^2.0.0+3
  avatar_glow:
  fluttertoast: ^8.1.2
  swipe_cards: ^2.0.0+1
  pin_code_fields: ^7.4.0
  image_picker: ^1.0.4
  path: ^1.8.3
  permission_handler: ^10.4.3
  http: ^0.13.5
  email_validator: ^2.1.17
  freezed_annotation: ^2.4.1
  json_annotation: ^4.0.0
  shimmer: ^2.0.0
  file_picker:
  video_player: ^2.7.2
  cached_network_image:
  video_thumbnail: ^0.5.3
  numeral: ^2.0.1
  # preload_page_view: ^0.1.6
  # should_rebuild: ^1.0.1
  like_button: ^2.0.5
  animated_icon_button: ^1.0.2
  # flutter_styled_toast: ^2.2.1
  # gallery_saver: ^2.3.2
  saver_gallery: ^2.0.1
  timeago:
  async:
  firebase_messaging:
  firebase_core:
  cloud_firestore:
  # flutter_paystack_payment: ^0.1.3+1
  # flutter_paystack: ^1.0.7
  # geolocator: ^9.0.2
  overlay_support: ^2.1.0
  restart_app: ^1.2.1
  firebase_analytics:
  connectivity_plus: ^3.0.3
  # location: ^4.3.0
  # app_settings: ^4.2.0
  country_code_picker: ^3.0.0
  expansion_tile_card: ^3.0.0
  url_launcher: ^6.1.10
  flutter_dotenv: ^5.0.2
  socket_io_client: ^2.0.2
  country_picker:
  dio: ^4.0.0
  path_provider: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie:
  # cached_video_preview: ^1.0.6
  pull_to_refresh: ^2.0.0
  # better_player: ^0.0.83
  # inview_notifier_list: ^3.0.0
  auto_size_text: ^3.0.0
  # new_version: ^0.3.1
  country_state_picker: null
  csc_picker: ^0.2.7
  get: ^4.6.5
  upgrader:
  flutter_phoenix:
  device_info_plus:
  fl_toast: ^3.2.0
  pay_with_paystack: ^1.0.6
  paystack_standard: ^0.0.8
  in_app_update: ^3.0.0
  # flutter_paystack_plus: ^1.0.2
  # visibility_detector: ^0.4.0+2
  # change_app_package_name: 1.0.0
  advance_image_picker: ^0.1.7+1
  video_trimmer: ^2.1.0
  pay: ^1.1.0
  image_cropper: ^2.0.3
  infinite_scroll_pagination: ^4.0.0
  scroll_edge_listener: ^0.1.1
  fast_immutable_collections: ^9.1.5
  easy_debounce: ^2.0.3
  chewie:
  preload_page_view: ^0.2.0
  photo_view: ^0.14.0
  smooth_video_progress: ^0.0.4
  persistent_bottom_nav_bar: ^5.0.2
  flutter_windowmanager: ^0.2.0
  apivideo_player: ^1.2.0
  flutter_vlc_player: ^7.4.0
  just_audio: ^0.9.35
  simple_animations: ^5.0.2
  custom_refresh_indicator: ^2.2.1
  extended_nested_scroll_view: ^6.1.2
  
  purchases_flutter: ^6.0.0
  just_audio_background: ^0.0.1-beta.10
  external_path: ^1.0.1









dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:



  flutter_lints: ^2.0.0
  json_serializable:
  hive_generator:


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/pic/MacaNacki.JPEG"




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pic/
    - assets/icon/
    - secret.env

